# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Account' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Account
 pod 'GoogleSignIn'

 pod 'FacebookCore'
 pod 'FacebookLogin'
 pod 'FacebookShare'

 pod 'Firebase/Core'
 pod 'Firebase/Auth'
end
